
-- -----------------------------
-- 表结构 `qinfo_message`
-- -----------------------------
CREATE TABLE IF NOT EXISTS `qinfo_message` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `title` varchar(20) NOT NULL DEFAULT '' COMMENT '别名',
  `alias_name` varchar(40) NOT NULL DEFAULT '',
  `name` varchar(40) NOT NULL DEFAULT '' COMMENT '消息名或标识',
  `typecode` int(10) NOT NULL,
  `mtype` varchar(40) NOT NULL DEFAULT '',
  `description` text COMMENT '消息描述',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态',
  `config` text COMMENT '配置',
  `create_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '安装时间',
  `write_name` varchar(40) DEFAULT '',
  `read_name` varchar(40) DEFAULT '',
  `mapping` varchar(40) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COMMENT='消息表';

-- -----------------------------
-- 表内记录 `qinfo_message`
-- -----------------------------
INSERT INTO `qinfo_message` VALUES ('3', '启动停止任务', 'w2s_clone', 'clone', '1064', 'W2S', '', '1', '{\"write\":[{\"name\":\"header\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":1},{\"name\":\"nWebId\",\"type\":\"TYPE_UINT64\",\"default\":\"1\",\"number\":2},{\"name\":\"nType\",\"type\":\"TYPE_UINT32\",\"default\":\"0\",\"number\":3},{\"name\":\"sUserId\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":4},{\"name\":\"nOperator\",\"type\":\"TYPE_UINT32\",\"default\":\"0\",\"number\":5}],\"read\":[{\"name\":\"header\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":1},{\"name\":\"nType\",\"type\":\"TYPE_UINT32\",\"default\":\"0\",\"number\":2},{\"name\":\"nState\",\"type\":\"TYPE_UINT32\",\"default\":\"0\",\"number\":3}]}', '1480566461', 'W2S_clone_write', 'W2S_clone_read', 'W2S_CLONE');
INSERT INTO `qinfo_message` VALUES ('4', '获取任务进度', 'w2s_clone_progress', 'clone_progress', '1062', 'W2S', '', '1', '{\"write\":[{\"name\":\"header\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":1},{\"name\":\"nWebId\",\"type\":\"TYPE_UINT64\",\"default\":\"\",\"number\":2},{\"name\":\"nType\",\"type\":\"TYPE_UINT32\",\"default\":\"\",\"number\":3},{\"name\":\"sUserId\",\"type\":\"TYPE_STRING\",\"default\":\"null\",\"number\":4}],\"read\":[{\"name\":\"header\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":1},{\"name\":\"nWebId\",\"type\":\"TYPE_UINT64\",\"default\":\"\",\"number\":2},{\"name\":\"nState\",\"type\":\"TYPE_UINT32\",\"default\":\"\",\"number\":3},{\"name\":\"nSystemType\",\"type\":\"TYPE_UINT32\",\"default\":\"\",\"number\":4},{\"name\":\"nDriveState\",\"type\":\"TYPE_UINT32\",\"default\":\"\",\"number\":5},{\"name\":\"nPowerState\",\"type\":\"TYPE_UINT32\",\"default\":\"\",\"number\":6},{\"name\":\"nSystemWorkState\",\"type\":\"TYPE_UINT32\",\"default\":\"\",\"number\":7},{\"name\":\"nEngineWorkState\",\"type\":\"TYPE_UINT32\",\"default\":\"\",\"number\":8},{\"name\":\"nSpeed\",\"type\":\"TYPE_UINT32\",\"default\":\"\",\"number\":9},{\"name\":\"nUsedTime\",\"type\":\"TYPE_UINT32\",\"default\":\"\",\"number\":10},{\"name\":\"nHigh\",\"type\":\"TYPE_UINT32\",\"default\":\"\",\"number\":11},{\"name\":\"nLow\",\"type\":\"TYPE_UINT32\",\"default\":\"\",\"number\":12},{\"name\":\"nIsUpdateDb\",\"type\":\"TYPE_UINT32\",\"default\":\"\",\"number\":13},{\"name\":\"nProgress\",\"type\":\"TYPE_UINT32\",\"default\":\"\",\"number\":14},{\"name\":\"nMirrorPartition\",\"type\":\"TYPE_UINT32\",\"default\":\"\",\"number\":15},{\"name\":\"sFileSystemDescription\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":16},{\"name\":\"sSystemWorkDescription\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":17},{\"name\":\"sUuid\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":18}]}', '1480566195', 'W2S_clone_progress_write', 'W2S_clone_progress_read', 'W2S_CLONE_STATE');
INSERT INTO `qinfo_message` VALUES ('2', '更新任务配置', 'w2s_clone_update', 'clone_update', '1057', 'W2S', '', '1', '{\"write\":[{\"name\":\"header\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":1},{\"name\":\"nWebId\",\"type\":\"TYPE_UINT64\",\"default\":\"0\",\"number\":2},{\"name\":\"nType\",\"type\":\"TYPE_UINT32\",\"default\":\"0\",\"number\":3},{\"name\":\"sUserId\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":4},{\"name\":\"sCloneId\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":5},{\"name\":\"StorageIp\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":6},{\"name\":\"DiskMap\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":7},{\"name\":\"MacAddr\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":8}]}', '1480644586', 'W2S_clone_update_write', '', 'W2S_UPDATE_CLONE');
INSERT INTO `qinfo_message` VALUES ('1', '任务初始化', 'w2s_clone_reset', 'clone_reset', '1061', 'W2S', '', '1', '{\"write\":[{\"name\":\"header\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":1},{\"name\":\"nWebId\",\"type\":\"TYPE_UINT64\",\"default\":\"0\",\"number\":2},{\"name\":\"nType\",\"type\":\"TYPE_UINT32\",\"default\":\"0\",\"number\":3},{\"name\":\"sUserId\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":4}],\"read\":[{\"name\":\"header\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":1},{\"name\":\"nType\",\"type\":\"TYPE_UINT32\",\"default\":\"0\",\"number\":2},{\"name\":\"nState\",\"type\":\"TYPE_UINT32\",\"default\":\"0\",\"number\":3}]}', '1480645788', 'W2S_clone_reset_write', 'W2S_clone_reset_read', 'W2S_RESET_CLIENT_SYSTEMID');
INSERT INTO `qinfo_message` VALUES ('5', '任务同步快照校验', 'w2s_clone_snap_syn', 'clone_snap_syn', '1065', 'W2S', '', '1', '{\"write\":[{\"name\":\"header\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":1},{\"name\":\"nWebId\",\"type\":\"TYPE_UINT64\",\"default\":\"0\",\"number\":2},{\"name\":\"nType\",\"type\":\"TYPE_UINT32\",\"default\":\"0\",\"number\":3},{\"name\":\"sUserId\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":4},{\"name\":\"nOperType\",\"type\":\"TYPE_UINT32\",\"default\":\"0\",\"number\":5}],\"read\":[{\"name\":\"header\",\"type\":\"TYPE_STRING\",\"default\":\"\",\"number\":1},{\"name\":\"nType\",\"type\":\"TYPE_UINT32\",\"default\":\"0\",\"number\":2},{\"name\":\"nState\",\"type\":\"TYPE_UINT32\",\"default\":\"0\",\"number\":3}]}', '1480646380', 'W2S_clone_snap_syn_write', 'W2S_clone_snap_syn_read', 'W2S_SNAP_SYN');
